name: CI

on: [push]

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set BOOST_ROOT
      shell: bash
      run: |
        echo "::set-env name=BOOST_ROOT::$BOOST_ROOT_1_72_0"
        echo "::set-env name=BOOST_INCLUDEDIR::$BOOST_ROOT_1_72_0/include"
        echo "::set-env name=BOOST_LIBRARYDIR::$BOOST_ROOT_1_72_0/lib"
        echo "::set-env name=Boost_NO_SYSTEM_PATHS::ON"
    - name: Debug prints
      shell: bash
      run: |
        echo $PATH
        echo $BOOST_ROOT
        echo $BOOST_ROOT_1_67_0
        echo $BOOST_LIBRARYDIR
        echo $Boost_NO_SYSTEM_PATHS
        echo $BOOST_INCLUDEDIR
        echo $BOOSTROOT
        echo $Boost_DIR
        echo foo
        ls -lah $BOOST_ROOT
        echo bar
        ls -lah $BOOST_ROOT/lib
        echo baz
        ls -lah $BOOST_ROOT/libs
    - uses: actions/checkout@v2
    - name: Build & install
      run: |
        mkdir build
        cd build
        cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
        cmake --build . --config Release --parallel 2
        cmake --install . --config Release
